<?php 
return [ 
'name' => 'Distribuidora de Cosmeticos San Marcos',
'website' => '#',
'company_phone' => '37569098',
'email_from' => 'danielvel1977@gmail.com',
'maintenance_mode' => '0',
'currency' => 'Q',
'shop_min_amount' => '25',
'shipping_method' => '2',
'shipping_default_value' => '35',
'shipping_amount_min' => '1000',
'to_go' => '1',
'social_facebook' => 'www.facebook.com',
'social_instagram' => '#',
'social_twitter' => '#',
'social_youtube' => '#',
'social_whatsapp' => '#',
'payment_method_cash' => '1',
'payment_method_transfer' => '1',
'payment_method_paypal' => '1',
'payment_method_credit_card' => '1',
'products_per_page' => '5',
'products_per_page_random' => '10',
'server_uploads_paths' => 'C:/desarrollos/tienda/public/uploads',
'server_uploads_user_paths' => 'C:/desarrollos/tienda/public/uploads_users',
'server_webapp_path' => 'C:/desarrollos/tienda_app/',
] 
?> 
